#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

readonly repo=shellbro/centos
readonly tag="$(cat VERSION)-$(date +%s)"

sudo docker pull "$repo:8"
sudo docker tag "$repo:8" "$repo:$tag"
sudo docker push "$repo:$tag"

git pull origin master
git tag "v$tag"
git push origin "v$tag"
