#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

readonly repo=shellbro/centos
readonly tag="$(cat VERSION)-$(date +%s)"

sudo docker pull "$repo:7"
sudo docker tag "$repo:7" "$repo:$tag"
sudo docker push "$repo:$tag"

git pull origin centos7
git tag "v$tag"
git push origin "v$tag"
