#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

readonly repo=shellbro/centos
readonly tag="$(cat VERSION)-$(date +%s)"

docker pull "$repo:7"
docker tag "$repo:7" "$repo:$tag"
docker push "$repo:$tag"

git pull origin master
git tag "v$tag"
git push origin "v$tag"
